<?php

use App\Http\Controllers\Web\Admin\AcademicYearController as AdminAcademicYearController;
use App\Http\Controllers\Web\Admin\AnnouncementController as AdminAnnouncementController;
use App\Http\Controllers\Web\Admin\AssignmentController as AdminAssignmentController;
use App\Http\Controllers\Web\Admin\AuditLogController;
use App\Http\Controllers\Web\Admin\CategoryController as AdminCategoryController;
use App\Http\Controllers\Web\Admin\CommsController;
use App\Http\Controllers\Web\Admin\CouponController as AdminCouponController;
use App\Http\Controllers\Web\Admin\CourseController as AdminCourseController;
use App\Http\Controllers\Web\Admin\CourseIntroVideoController;
use App\Http\Controllers\Web\Admin\DashboardExportController;
use App\Http\Controllers\Web\Admin\EnrollmentRequestController as AdminEnrollmentRequestController;
use App\Http\Controllers\Web\Admin\FinanceOverviewController;
use App\Http\Controllers\Web\Admin\GroupController as AdminGroupController;
use App\Http\Controllers\Web\Admin\HomeController as AdminHomeController;
use App\Http\Controllers\Web\Admin\ImpersonationController;
use App\Http\Controllers\Web\Admin\LessonController as AdminLessonController;
use App\Http\Controllers\Web\Admin\LessonMediaController as AdminLessonMediaController;
use App\Http\Controllers\Web\Admin\MarketingOverviewController;
use App\Http\Controllers\Web\Admin\OpsController;
use App\Http\Controllers\Web\Admin\OrderController as AdminOrderController;
use App\Http\Controllers\Web\Admin\PaymentController as AdminPaymentController;
use App\Http\Controllers\Web\Admin\QuestionController as AdminQuestionController;
use App\Http\Controllers\Web\Admin\QuizController as AdminQuizController;
use App\Http\Controllers\Web\Admin\ReportController as AdminReportController;
use App\Http\Controllers\Web\Admin\RoleController as AdminRoleController;
use App\Http\Controllers\Web\Admin\SecurityController;
use App\Http\Controllers\Web\Admin\SemesterController as AdminSemesterController;
use App\Http\Controllers\Web\Admin\SettingsController as AdminSettingsController;
use App\Http\Controllers\Web\Admin\StudentBulkController;
use App\Http\Controllers\Web\Admin\StudentController as AdminStudentController;
use App\Http\Controllers\Web\Admin\SupportOverviewController;
use App\Http\Controllers\Web\Admin\SystemLogController;
use App\Http\Controllers\Web\Admin\TeacherController as AdminTeacherController;
use App\Http\Controllers\Web\Admin\TeamOverviewController;
use App\Http\Controllers\Web\Admin\TelegramController as AdminTelegramController;
use App\Http\Controllers\Web\Admin\UserController as AdminUserController;
use App\Http\Controllers\Web\Auth\AuthenticatedSessionController;
use App\Http\Controllers\Web\Auth\NewPasswordController;
use App\Http\Controllers\Web\Auth\PasswordResetLinkController;
use App\Http\Controllers\Web\Auth\RegisteredUserController;
use App\Http\Controllers\Web\DashboardPickerController;
use App\Http\Controllers\Web\Finance\ExpenseController;
use App\Http\Controllers\Web\Finance\ForecastController;
use App\Http\Controllers\Web\Finance\HomeController as FinanceHomeController;
use App\Http\Controllers\Web\Finance\PayrollController;
use App\Http\Controllers\Web\Finance\ProfitController;
use App\Http\Controllers\Web\Finance\RefundController;
use App\Http\Controllers\Web\Finance\ReportController as FinanceReportController;
use App\Http\Controllers\Web\Finance\RevenueController;
use App\Http\Controllers\Web\Finance\SubscriptionController;
use App\Http\Controllers\Web\Finance\TransactionController;
use App\Http\Controllers\Web\Instructor\AnnouncementController as InstructorAnnouncementController;
use App\Http\Controllers\Web\Instructor\AssignmentController;
use App\Http\Controllers\Web\Instructor\CalendarController as InstructorCalendarController;
use App\Http\Controllers\Web\Instructor\CourseController as InstructorCourseController;
use App\Http\Controllers\Web\Instructor\DashboardController as InstructorDashboardController;
use App\Http\Controllers\Web\Instructor\HomeController as InstructorHomeController;
use App\Http\Controllers\Web\Instructor\LessonController as InstructorLessonController;
use App\Http\Controllers\Web\Instructor\LiveSessionController;
use App\Http\Controllers\Web\Instructor\MediaUploadController;
use App\Http\Controllers\Web\Instructor\MessageController;
use App\Http\Controllers\Web\Instructor\QuizController as InstructorQuizController;
use App\Http\Controllers\Web\Instructor\ReportController as InstructorReportController;
use App\Http\Controllers\Web\Instructor\SettingsController as InstructorSettingsController;
use App\Http\Controllers\Web\Instructor\StudentRosterController;
use App\Http\Controllers\Web\Marketing\AmbassadorController;
use App\Http\Controllers\Web\Marketing\AnalyticsController as MarketingAnalyticsController;
use App\Http\Controllers\Web\Marketing\CampaignController;
use App\Http\Controllers\Web\Marketing\ConversionController;
use App\Http\Controllers\Web\Marketing\CouponController;
use App\Http\Controllers\Web\Marketing\HomeController as MarketingHomeController;
use App\Http\Controllers\Web\Marketing\LeadController;
use App\Http\Controllers\Web\Marketing\ReferralController;
use App\Http\Controllers\Web\Public\ContactController;
use App\Http\Controllers\Web\Public\CourseCatalogController;
use App\Http\Controllers\Web\Public\FaqController as PublicFaqController;
use App\Http\Controllers\Web\Public\HomeController as PublicHomeController;
use App\Http\Controllers\Web\Public\InstructorDirectoryController;
use App\Http\Controllers\Web\Public\PageController;
use App\Http\Controllers\Web\Staff\CourseRequestController as StaffCourseRequestController;
use App\Http\Controllers\Web\Student\AchievementController;
use App\Http\Controllers\Web\Student\CalendarController as StudentCalendarController;
use App\Http\Controllers\Web\Student\CourseController as StudentCourseController;
use App\Http\Controllers\Web\Student\CourseRequestController as StudentCourseRequestController;
use App\Http\Controllers\Web\Student\HomeController as StudentHomeController;
use App\Http\Controllers\Web\Student\LessonController as StudentLessonController;
use App\Http\Controllers\Web\Student\MediaController;
use App\Http\Controllers\Web\Student\NotificationController;
use App\Http\Controllers\Web\Student\ProfileController;
use App\Http\Controllers\Web\Student\ProgressController;
use App\Http\Controllers\Web\Student\QuizController as StudentQuizController;
use App\Http\Controllers\Web\Student\SettingsController as StudentSettingsController;
use App\Http\Controllers\Web\Student\SupportController as StudentSupportController;
use App\Http\Controllers\Web\Support\ChatController;
use App\Http\Controllers\Web\Support\FaqController;
use App\Http\Controllers\Web\Support\HomeController as SupportHomeController;
use App\Http\Controllers\Web\Support\ReportController as SupportReportController;
use App\Http\Controllers\Web\Support\StudentLookupController;
use App\Http\Controllers\Web\Support\TicketController;
use App\Http\Controllers\Web\Team\AnnouncementController as TeamAnnouncementController;
use App\Http\Controllers\Web\Team\AttendanceController;
use App\Http\Controllers\Web\Team\FileController as TeamFileController;
use App\Http\Controllers\Web\Team\GoalController;
use App\Http\Controllers\Web\Team\HomeController as TeamHomeController;
use App\Http\Controllers\Web\Team\MeetingController;
use App\Http\Controllers\Web\Team\ReportController as TeamReportController;
use App\Http\Controllers\Web\Team\TaskController;
use Illuminate\Support\Facades\Route;

Route::get('/', [PublicHomeController::class, 'index'])->name('home');
Route::get('/courses', [CourseCatalogController::class, 'index'])->name('public.courses.index');
Route::get('/courses/{course}', [CourseCatalogController::class, 'show'])->name('public.courses.show');
Route::get('/about', [PageController::class, 'about'])->name('public.about');
Route::get('/how-it-works', [PageController::class, 'howItWorks'])->name('public.how-it-works');
Route::get('/instructors', [InstructorDirectoryController::class, 'index'])->name('public.instructors');
Route::get('/faq', [PublicFaqController::class, 'index'])->name('public.faq');
Route::get('/contact', [ContactController::class, 'create'])->name('public.contact');
Route::post('/contact', [ContactController::class, 'store'])->name('public.contact.store');
Route::get('/privacy', [PageController::class, 'privacy'])->name('public.privacy');
Route::get('/terms', [PageController::class, 'terms'])->name('public.terms');

Route::middleware('guest')->group(function () {
    Route::get('/login', [AuthenticatedSessionController::class, 'create'])->name('login');
    Route::post('/login', [AuthenticatedSessionController::class, 'store']);
    Route::get('/register', [RegisteredUserController::class, 'create'])->name('register');
    Route::post('/register', [RegisteredUserController::class, 'store']);
    Route::get('/forgot-password', [PasswordResetLinkController::class, 'create'])->name('password.request');
    Route::post('/forgot-password', [PasswordResetLinkController::class, 'store'])->name('password.email');
    Route::get('/reset-password/{token}', [NewPasswordController::class, 'create'])->name('password.reset');
    Route::post('/reset-password', [NewPasswordController::class, 'store'])->name('password.store');
});

Route::post('/logout', [AuthenticatedSessionController::class, 'destroy'])->middleware('auth')->name('logout');

Route::middleware('auth')->group(function () {
    Route::get('/dashboard', [DashboardPickerController::class, 'redirect'])->name('dashboard.redirect');
    Route::get('/dashboard-picker', [DashboardPickerController::class, 'redirect'])->name('dashboard.picker');
    Route::post('/dashboard-picker', [DashboardPickerController::class, 'choose'])->name('dashboard.choose');
    Route::post('/impersonation/leave', [ImpersonationController::class, 'leave'])->name('impersonation.leave');

    Route::middleware('dashboard:student')->prefix('student')->name('student.')->group(function () {
        Route::get('/', [StudentHomeController::class, 'index'])->name('home');
        Route::get('/courses', [StudentCourseController::class, 'index'])->name('courses.index');
        Route::get('/courses/{course}', [StudentCourseController::class, 'show'])->name('courses.show');
        Route::get('/lessons/{lesson}', [StudentLessonController::class, 'show'])->name('lessons.show');
        Route::post('/lessons/{lesson}/progress', [StudentLessonController::class, 'progress'])->name('lessons.progress');
        Route::post('/lessons/{lesson}/complete', [StudentLessonController::class, 'complete'])->name('lessons.complete');
        Route::get('/media/{asset}', [MediaController::class, 'show'])->name('media.show');
        Route::get('/quizzes/{quiz}', [StudentQuizController::class, 'show'])->name('quizzes.show');
        Route::post('/quizzes/{quiz}/attempts', [StudentQuizController::class, 'start'])->name('quizzes.start');
        Route::post('/quiz-attempts/{attempt}/submit', [StudentQuizController::class, 'submit'])->name('quizzes.submit');
        Route::get('/quiz-attempts/{attempt}/result', [StudentQuizController::class, 'result'])->name('quizzes.result');
        Route::get('/course-requests', [StudentCourseRequestController::class, 'index'])->name('course-requests.index');
        Route::post('/course-requests', [StudentCourseRequestController::class, 'store'])->name('course-requests.store');
        Route::get('/progress', [ProgressController::class, 'index'])->name('progress');
        Route::get('/achievements', [AchievementController::class, 'index'])->name('achievements');
        Route::get('/notifications', [NotificationController::class, 'index'])->name('notifications');
        Route::get('/calendar', [StudentCalendarController::class, 'index'])->name('calendar');
        Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
        Route::put('/profile', [ProfileController::class, 'update'])->name('profile.update');
        Route::get('/settings', [StudentSettingsController::class, 'edit'])->name('settings.edit');
        Route::put('/settings', [StudentSettingsController::class, 'update'])->name('settings.update');
        Route::get('/support', [StudentSupportController::class, 'index'])->name('support.index');
        Route::post('/support', [StudentSupportController::class, 'store'])->name('support.store');
    });

    Route::middleware('permission:enrollments.approve')->prefix('staff')->name('staff.')->group(function () {
        Route::get('/course-requests', [StaffCourseRequestController::class, 'index'])->name('course-requests.index');
        Route::post('/course-requests/{courseAccessRequest}/approve', [StaffCourseRequestController::class, 'approve'])->name('course-requests.approve');
        Route::post('/course-requests/{courseAccessRequest}/reject', [StaffCourseRequestController::class, 'reject'])->name('course-requests.reject');
    });

    Route::middleware('dashboard:instructor')->prefix('instructor')->name('instructor.')->group(function () {
        Route::get('/', [InstructorHomeController::class, 'index'])->name('home');
        Route::get('/dashboard', [InstructorDashboardController::class, 'index'])->name('dashboard');
        Route::get('/courses', [InstructorCourseController::class, 'index'])->name('courses.index');
        Route::get('/courses/create', [InstructorCourseController::class, 'create'])->name('courses.create');
        Route::post('/courses', [InstructorCourseController::class, 'store'])->name('courses.store');
        Route::get('/courses/{course}', [InstructorCourseController::class, 'show'])->name('courses.show');
        Route::post('/courses/{course}/lessons', [InstructorLessonController::class, 'store'])->name('lessons.store');
        Route::post('/courses/{course}/quizzes', [InstructorQuizController::class, 'store'])->name('quizzes.store');
        Route::post('/lessons/{lesson}/media', [MediaUploadController::class, 'store'])->name('media.store');
        Route::get('/students', [StudentRosterController::class, 'index'])->name('students.index');
        Route::get('/announcements', [InstructorAnnouncementController::class, 'index'])->name('announcements.index');
        Route::post('/announcements', [InstructorAnnouncementController::class, 'store'])->name('announcements.store');
        Route::get('/messages', [MessageController::class, 'index'])->name('messages.index');
        Route::get('/live-sessions', [LiveSessionController::class, 'index'])->name('live-sessions.index');
        Route::post('/live-sessions', [LiveSessionController::class, 'store'])->name('live-sessions.store');
        Route::get('/reports', [InstructorReportController::class, 'index'])->name('reports.index');
        Route::get('/calendar', [InstructorCalendarController::class, 'index'])->name('calendar.index');
        Route::get('/settings', [InstructorSettingsController::class, 'index'])->name('settings.index');
        Route::get('/assignments', [AssignmentController::class, 'index'])->name('assignments.index');
    });

    Route::middleware('dashboard:finance')->prefix('finance')->name('finance.')->group(function () {
        Route::get('/', [FinanceHomeController::class, 'index'])->name('home');
        Route::get('/transactions', [TransactionController::class, 'index'])->name('transactions.index');
        Route::get('/subscriptions', [SubscriptionController::class, 'index'])->name('subscriptions.index');
        Route::get('/refunds', [RefundController::class, 'index'])->name('refunds.index');
        Route::post('/refunds', [RefundController::class, 'store'])->name('refunds.store');
        Route::get('/expenses', [ExpenseController::class, 'index'])->name('expenses.index');
        Route::get('/payroll', [PayrollController::class, 'index'])->name('payroll.index');
        Route::get('/forecast', [ForecastController::class, 'index'])->name('forecast.index');
        Route::get('/profit', [ProfitController::class, 'index'])->name('profit.index');
        Route::get('/revenue', [RevenueController::class, 'index'])->name('revenue.index');
        Route::post('/reports', [FinanceReportController::class, 'store'])->name('reports.store');
    });

    Route::middleware('dashboard:marketing')->prefix('marketing')->name('marketing.')->group(function () {
        Route::get('/', [MarketingHomeController::class, 'index'])->name('home');
        Route::get('/campaigns', [CampaignController::class, 'index'])->name('campaigns.index');
        Route::get('/campaigns/create', [CampaignController::class, 'create'])->name('campaigns.create');
        Route::post('/campaigns', [CampaignController::class, 'store'])->name('campaigns.store');
        Route::get('/coupons', [CouponController::class, 'index'])->name('coupons.index');
        Route::post('/coupons', [CouponController::class, 'store'])->name('coupons.store');
        Route::get('/referrals', [ReferralController::class, 'index'])->name('referrals.index');
        Route::get('/ambassadors', [AmbassadorController::class, 'index'])->name('ambassadors.index');
        Route::get('/leads', [LeadController::class, 'index'])->name('leads.index');
        Route::get('/conversions', [ConversionController::class, 'index'])->name('conversions.index');
        Route::get('/analytics', [MarketingAnalyticsController::class, 'index'])->name('analytics.index');
    });

    Route::middleware('dashboard:team')->prefix('team')->name('team.')->group(function () {
        Route::get('/', [TeamHomeController::class, 'index'])->name('home');
        Route::get('/tasks', [TaskController::class, 'index'])->name('tasks.index');
        Route::patch('/tasks/{task}', [TaskController::class, 'update'])->name('tasks.update');
        Route::get('/announcements', [TeamAnnouncementController::class, 'index'])->name('announcements.index');
        Route::get('/files', [TeamFileController::class, 'index'])->name('files.index');
        Route::get('/meetings', [MeetingController::class, 'index'])->name('meetings.index');
        Route::get('/goals', [GoalController::class, 'index'])->name('goals.index');
        Route::get('/attendance', [AttendanceController::class, 'index'])->name('attendance.index');
        Route::get('/reports', [TeamReportController::class, 'index'])->name('reports.index');
    });

    Route::middleware('dashboard:support')->prefix('support')->name('support.')->group(function () {
        Route::get('/', [SupportHomeController::class, 'index'])->name('home');
        Route::get('/tickets', [TicketController::class, 'index'])->name('tickets.index');
        Route::get('/tickets/{ticket}', [TicketController::class, 'show'])->name('tickets.show');
        Route::post('/tickets/{ticket}/reply', [TicketController::class, 'reply'])->name('tickets.reply');
        Route::post('/tickets/{ticket}/close', [TicketController::class, 'close'])->name('tickets.close');
        Route::get('/chat', [ChatController::class, 'index'])->name('chat.index');
        Route::get('/students', [StudentLookupController::class, 'index'])->name('students.index');
        Route::get('/faq', [FaqController::class, 'index'])->name('faq.index');
        Route::post('/faq', [FaqController::class, 'store'])->name('faq.store');
        Route::get('/reports', [SupportReportController::class, 'index'])->name('reports.index');
    });

    Route::middleware('dashboard:admin')->prefix('admin')->name('admin.')->group(function () {
        Route::get('/', [AdminHomeController::class, 'index'])->name('home');
        Route::post('/dashboard/export/pdf', [DashboardExportController::class, 'exportPdf'])->name('dashboard.export.pdf');
        Route::post('/dashboard/export/excel', [DashboardExportController::class, 'exportExcel'])->name('dashboard.export.excel');

        Route::get('/users', [AdminUserController::class, 'index'])->name('users.index');
        Route::get('/users/create', [AdminUserController::class, 'create'])->name('users.create');
        Route::post('/users', [AdminUserController::class, 'store'])->name('users.store');
        Route::get('/users/{user}/edit', [AdminUserController::class, 'edit'])->name('users.edit');
        Route::put('/users/{user}', [AdminUserController::class, 'update'])->name('users.update');
        Route::delete('/users/{user}', [AdminUserController::class, 'destroy'])->name('users.destroy');
        Route::post('/users/{user}/impersonate', [ImpersonationController::class, 'start'])->name('users.impersonate');

        Route::get('/students/bulk/export', [StudentBulkController::class, 'export'])->name('students.bulk.export');
        Route::post('/students/bulk/destroy', [StudentBulkController::class, 'destroy'])->name('students.bulk.destroy');
        Route::post('/students/bulk/activate', [StudentBulkController::class, 'activate'])->name('students.bulk.activate');
        Route::post('/students/bulk/deactivate', [StudentBulkController::class, 'deactivate'])->name('students.bulk.deactivate');
        Route::post('/students/bulk/assign-course', [StudentBulkController::class, 'assignCourse'])->name('students.bulk.assign-course');
        Route::get('/students', [AdminStudentController::class, 'index'])->name('students.index');
        Route::get('/students/create', [AdminStudentController::class, 'create'])->name('students.create');
        Route::post('/students', [AdminStudentController::class, 'store'])->name('students.store');
        Route::get('/students/{student}', [AdminStudentController::class, 'show'])->name('students.show');
        Route::get('/students/{student}/edit', [AdminStudentController::class, 'edit'])->name('students.edit');
        Route::put('/students/{student}', [AdminStudentController::class, 'update'])->name('students.update');
        Route::delete('/students/{student}', [AdminStudentController::class, 'destroy'])->name('students.destroy');
        Route::post('/students/{student}/suspend', [AdminStudentController::class, 'suspend'])->name('students.suspend');
        Route::post('/students/{student}/activate', [AdminStudentController::class, 'activate'])->name('students.activate');
        Route::post('/students/{student}/reset-password', [AdminStudentController::class, 'resetPassword'])->name('students.reset-password');
        Route::post('/students/{student}/assign-course', [AdminStudentController::class, 'assignCourse'])->name('students.assign-course');
        Route::post('/students/{student}/remove-course', [AdminStudentController::class, 'removeCourse'])->name('students.remove-course');
        Route::post('/students/{student}/placement', [AdminStudentController::class, 'updatePlacement'])->name('students.placement');
        Route::post('/students/{student}/notes', [AdminStudentController::class, 'updateNotes'])->name('students.notes');
        Route::post('/students/{student}/impersonate', [ImpersonationController::class, 'start'])->name('students.impersonate');

        Route::get('/courses', [AdminCourseController::class, 'index'])->name('courses.index');
        Route::get('/courses/create', [AdminCourseController::class, 'create'])->name('courses.create');
        Route::post('/courses', [AdminCourseController::class, 'store'])->name('courses.store');
        Route::get('/courses/{course}', [AdminCourseController::class, 'show'])->name('courses.show');
        Route::get('/courses/{course}/edit', [AdminCourseController::class, 'edit'])->name('courses.edit');
        Route::put('/courses/{course}', [AdminCourseController::class, 'update'])->name('courses.update');
        Route::delete('/courses/{course}', [AdminCourseController::class, 'destroy'])->name('courses.destroy');
        Route::post('/courses/{course}/archive', [AdminCourseController::class, 'archive'])->name('courses.archive');
        Route::post('/courses/{course}/duplicate', [AdminCourseController::class, 'duplicate'])->name('courses.duplicate');
        Route::post('/courses/{course}/publish', [AdminCourseController::class, 'publish'])->name('courses.publish');
        Route::post('/courses/{course}/hide', [AdminCourseController::class, 'hide'])->name('courses.hide');
        Route::post('/courses/{course}/assign-teacher', [AdminCourseController::class, 'assignTeacher'])->name('courses.assign-teacher');
        Route::post('/courses/{course}/assign-semester', [AdminCourseController::class, 'assignSemester'])->name('courses.assign-semester');
        Route::post('/courses/{course}/enroll-student', [AdminCourseController::class, 'enrollStudent'])->name('courses.enroll-student');
        Route::post('/courses/{course}/unenroll-student', [AdminCourseController::class, 'unenrollStudent'])->name('courses.unenroll-student');
        Route::post('/courses/{course}/intro-video/init', [CourseIntroVideoController::class, 'init'])->name('courses.intro-video.init');
        Route::get('/courses/{course}/intro-video/uploads/{upload}', [CourseIntroVideoController::class, 'status'])->name('courses.intro-video.status');
        Route::post('/courses/{course}/intro-video/uploads/{upload}/chunk', [CourseIntroVideoController::class, 'chunk'])->name('courses.intro-video.chunk');
        Route::post('/courses/{course}/intro-video/uploads/{upload}/complete', [CourseIntroVideoController::class, 'complete'])->name('courses.intro-video.complete');
        Route::get('/courses/{course}/intro-video/stream', [CourseIntroVideoController::class, 'stream'])->name('courses.intro-video.stream');
        Route::delete('/courses/{course}/intro-video', [CourseIntroVideoController::class, 'destroy'])->name('courses.intro-video.destroy');

        Route::get('/categories', [AdminCategoryController::class, 'index'])->name('categories.index');
        Route::get('/categories/create', [AdminCategoryController::class, 'create'])->name('categories.create');
        Route::post('/categories', [AdminCategoryController::class, 'store'])->name('categories.store');
        Route::get('/categories/{category}/edit', [AdminCategoryController::class, 'edit'])->name('categories.edit');
        Route::put('/categories/{category}', [AdminCategoryController::class, 'update'])->name('categories.update');
        Route::delete('/categories/{category}', [AdminCategoryController::class, 'destroy'])->name('categories.destroy');
        Route::post('/categories/{category}/merge', [AdminCategoryController::class, 'merge'])->name('categories.merge');
        Route::post('/categories/{category}/archive', [AdminCategoryController::class, 'archive'])->name('categories.archive');
        Route::post('/categories/{category}/restore', [AdminCategoryController::class, 'restore'])->name('categories.restore');

        Route::get('/lessons', [AdminLessonController::class, 'index'])->name('lessons.index');
        Route::get('/lessons/create', [AdminLessonController::class, 'create'])->name('lessons.create');
        Route::post('/lessons', [AdminLessonController::class, 'store'])->name('lessons.store');
        Route::post('/lessons/reorder', [AdminLessonController::class, 'reorder'])->name('lessons.reorder');
        Route::get('/lessons/{lesson}', [AdminLessonController::class, 'show'])->name('lessons.show');
        Route::get('/lessons/{lesson}/edit', [AdminLessonController::class, 'edit'])->name('lessons.edit');
        Route::put('/lessons/{lesson}', [AdminLessonController::class, 'update'])->name('lessons.update');
        Route::delete('/lessons/{lesson}', [AdminLessonController::class, 'destroy'])->name('lessons.destroy');
        Route::post('/lessons/{lesson}/lock', [AdminLessonController::class, 'lock'])->name('lessons.lock');
        Route::post('/lessons/{lesson}/unlock', [AdminLessonController::class, 'unlock'])->name('lessons.unlock');
        Route::post('/lessons/{lesson}/duplicate', [AdminLessonController::class, 'duplicate'])->name('lessons.duplicate');
        Route::post('/lessons/{lesson}/schedule-publish', [AdminLessonController::class, 'schedulePublish'])->name('lessons.schedule-publish');
        Route::post('/lessons/{lesson}/attach-quiz', [AdminLessonController::class, 'attachQuiz'])->name('lessons.attach-quiz');
        Route::post('/lessons/{lesson}/media', [AdminLessonMediaController::class, 'store'])->name('lessons.media.store');
        Route::get('/lessons/{lesson}/media/{media}', [AdminLessonMediaController::class, 'show'])->name('lessons.media.show');
        Route::delete('/lessons/{lesson}/media/{media}', [AdminLessonMediaController::class, 'destroy'])->name('lessons.media.destroy');

        Route::get('/quizzes', [AdminQuizController::class, 'index'])->name('quizzes.index');
        Route::get('/quizzes/create', [AdminQuizController::class, 'create'])->name('quizzes.create');
        Route::post('/quizzes', [AdminQuizController::class, 'store'])->name('quizzes.store');
        Route::get('/quizzes/{quiz}', [AdminQuizController::class, 'show'])->name('quizzes.show');
        Route::get('/quizzes/{quiz}/edit', [AdminQuizController::class, 'edit'])->name('quizzes.edit');
        Route::put('/quizzes/{quiz}', [AdminQuizController::class, 'update'])->name('quizzes.update');
        Route::delete('/quizzes/{quiz}', [AdminQuizController::class, 'destroy'])->name('quizzes.destroy');
        Route::post('/quizzes/{quiz}/duplicate', [AdminQuizController::class, 'duplicate'])->name('quizzes.duplicate');
        Route::post('/quizzes/{quiz}/publish', [AdminQuizController::class, 'publish'])->name('quizzes.publish');
        Route::post('/quizzes/{quiz}/unpublish', [AdminQuizController::class, 'unpublish'])->name('quizzes.unpublish');
        Route::post('/quizzes/{quiz}/assign-course', [AdminQuizController::class, 'assignCourse'])->name('quizzes.assign-course');
        Route::post('/quizzes/{quiz}/assign-lesson', [AdminQuizController::class, 'assignLesson'])->name('quizzes.assign-lesson');
        Route::post('/quizzes/{quiz}/randomize', [AdminQuizController::class, 'randomize'])->name('quizzes.randomize');
        Route::post('/quizzes/{quiz}/questions', [AdminQuestionController::class, 'store'])->name('quizzes.questions.store');
        Route::post('/quizzes/{quiz}/questions/reorder', [AdminQuestionController::class, 'reorder'])->name('quizzes.questions.reorder');
        Route::put('/quizzes/{quiz}/questions/{question}', [AdminQuestionController::class, 'update'])->name('quizzes.questions.update');
        Route::delete('/quizzes/{quiz}/questions/{question}', [AdminQuestionController::class, 'destroy'])->name('quizzes.questions.destroy');

        Route::get('/assignments', [AdminAssignmentController::class, 'index'])->name('assignments.index');
        Route::get('/assignments/create', [AdminAssignmentController::class, 'create'])->name('assignments.create');
        Route::post('/assignments', [AdminAssignmentController::class, 'store'])->name('assignments.store');
        Route::get('/assignments/{assignment}', [AdminAssignmentController::class, 'show'])->name('assignments.show');
        Route::get('/assignments/{assignment}/edit', [AdminAssignmentController::class, 'edit'])->name('assignments.edit');
        Route::put('/assignments/{assignment}', [AdminAssignmentController::class, 'update'])->name('assignments.update');
        Route::delete('/assignments/{assignment}', [AdminAssignmentController::class, 'destroy'])->name('assignments.destroy');
        Route::post('/assignments/{assignment}/submissions/{submission}/grade', [AdminAssignmentController::class, 'gradeSubmission'])->name('assignments.submissions.grade');
        Route::post('/assignments/{assignment}/submissions/{submission}/resubmit', [AdminAssignmentController::class, 'requestResubmit'])->name('assignments.submissions.resubmit');

        Route::get('/orders', [AdminOrderController::class, 'index'])->name('orders.index');
        Route::get('/orders/export', [AdminOrderController::class, 'export'])->name('orders.export');
        Route::get('/orders/{order}', [AdminOrderController::class, 'show'])->name('orders.show');
        Route::get('/orders/{order}/invoice', [AdminOrderController::class, 'invoice'])->name('orders.invoice');
        Route::post('/orders/{order}/approve', [AdminOrderController::class, 'approve'])->name('orders.approve');
        Route::post('/orders/{order}/reject', [AdminOrderController::class, 'reject'])->name('orders.reject');
        Route::post('/orders/{order}/refund', [AdminOrderController::class, 'refund'])->name('orders.refund');

        Route::get('/payments', [AdminPaymentController::class, 'index'])->name('payments.index');
        Route::get('/payments/export', [AdminPaymentController::class, 'export'])->name('payments.export');
        Route::post('/payments', [AdminPaymentController::class, 'store'])->name('payments.store');
        Route::post('/payments/{payment}/verify', [AdminPaymentController::class, 'verify'])->name('payments.verify');
        Route::post('/payments/{payment}/approve', [AdminPaymentController::class, 'approve'])->name('payments.approve');
        Route::post('/payments/{payment}/reject', [AdminPaymentController::class, 'reject'])->name('payments.reject');
        Route::post('/payments/{payment}/refund', [AdminPaymentController::class, 'refund'])->name('payments.refund');

        Route::get('/coupons', [AdminCouponController::class, 'index'])->name('coupons.index');
        Route::get('/coupons/create', [AdminCouponController::class, 'create'])->name('coupons.create');
        Route::post('/coupons', [AdminCouponController::class, 'store'])->name('coupons.store');
        Route::post('/coupons/generate', [AdminCouponController::class, 'generate'])->name('coupons.generate');
        Route::get('/coupons/{coupon}/edit', [AdminCouponController::class, 'edit'])->name('coupons.edit');
        Route::put('/coupons/{coupon}', [AdminCouponController::class, 'update'])->name('coupons.update');
        Route::delete('/coupons/{coupon}', [AdminCouponController::class, 'destroy'])->name('coupons.destroy');
        Route::post('/coupons/{coupon}/activate', [AdminCouponController::class, 'activate'])->name('coupons.activate');
        Route::post('/coupons/{coupon}/deactivate', [AdminCouponController::class, 'deactivate'])->name('coupons.deactivate');
        Route::post('/coupons/{coupon}/duplicate', [AdminCouponController::class, 'duplicate'])->name('coupons.duplicate');
        Route::post('/coupons/{coupon}/limit-usage', [AdminCouponController::class, 'limitUsage'])->name('coupons.limit-usage');
        Route::post('/coupons/{coupon}/assign-course', [AdminCouponController::class, 'assignCourse'])->name('coupons.assign-course');

        Route::get('/teachers', [AdminTeacherController::class, 'index'])->name('teachers.index');
        Route::get('/teachers/create', [AdminTeacherController::class, 'create'])->name('teachers.create');
        Route::post('/teachers', [AdminTeacherController::class, 'store'])->name('teachers.store');
        Route::get('/teachers/{teacher}', [AdminTeacherController::class, 'show'])->name('teachers.show');
        Route::get('/teachers/{teacher}/edit', [AdminTeacherController::class, 'edit'])->name('teachers.edit');
        Route::get('/teachers/{teacher}/analytics', [AdminTeacherController::class, 'analytics'])->name('teachers.analytics');
        Route::put('/teachers/{teacher}', [AdminTeacherController::class, 'update'])->name('teachers.update');
        Route::delete('/teachers/{teacher}', [AdminTeacherController::class, 'destroy'])->name('teachers.destroy');
        Route::post('/teachers/{teacher}/suspend', [AdminTeacherController::class, 'suspend'])->name('teachers.suspend');
        Route::post('/teachers/{teacher}/activate', [AdminTeacherController::class, 'activate'])->name('teachers.activate');
        Route::post('/teachers/{teacher}/assign-courses', [AdminTeacherController::class, 'assignCourses'])->name('teachers.assign-courses');

        Route::get('/academic-years', [AdminAcademicYearController::class, 'index'])->name('academic-years.index');
        Route::get('/academic-years/create', [AdminAcademicYearController::class, 'create'])->name('academic-years.create');
        Route::post('/academic-years', [AdminAcademicYearController::class, 'store'])->name('academic-years.store');
        Route::get('/academic-years/{academicYear}/edit', [AdminAcademicYearController::class, 'edit'])->name('academic-years.edit');
        Route::put('/academic-years/{academicYear}', [AdminAcademicYearController::class, 'update'])->name('academic-years.update');
        Route::delete('/academic-years/{academicYear}', [AdminAcademicYearController::class, 'destroy'])->name('academic-years.destroy');

        Route::get('/semesters', [AdminSemesterController::class, 'index'])->name('semesters.index');
        Route::get('/semesters/create', [AdminSemesterController::class, 'create'])->name('semesters.create');
        Route::post('/semesters', [AdminSemesterController::class, 'store'])->name('semesters.store');
        Route::get('/semesters/{semester}/edit', [AdminSemesterController::class, 'edit'])->name('semesters.edit');
        Route::put('/semesters/{semester}', [AdminSemesterController::class, 'update'])->name('semesters.update');
        Route::delete('/semesters/{semester}', [AdminSemesterController::class, 'destroy'])->name('semesters.destroy');

        Route::get('/groups', [AdminGroupController::class, 'index'])->name('groups.index');
        Route::get('/groups/create', [AdminGroupController::class, 'create'])->name('groups.create');
        Route::post('/groups', [AdminGroupController::class, 'store'])->name('groups.store');
        Route::get('/groups/{group}', [AdminGroupController::class, 'show'])->name('groups.show');
        Route::get('/groups/{group}/edit', [AdminGroupController::class, 'edit'])->name('groups.edit');
        Route::put('/groups/{group}', [AdminGroupController::class, 'update'])->name('groups.update');
        Route::delete('/groups/{group}', [AdminGroupController::class, 'destroy'])->name('groups.destroy');
        Route::post('/groups/{group}/attach', [AdminGroupController::class, 'attachMember'])->name('groups.attach');
        Route::delete('/groups/{group}/members/{user}', [AdminGroupController::class, 'detachMember'])->name('groups.detach');

        Route::get('/telegram', [AdminTelegramController::class, 'index'])->name('telegram.index');
        Route::post('/telegram', [AdminTelegramController::class, 'store'])->name('telegram.store');
        Route::post('/telegram/{telegramGroup}/attach-course', [AdminTelegramController::class, 'attachCourse'])->name('telegram.attach-course');
        Route::post('/telegram/{telegramGroup}/generate-invite', [AdminTelegramController::class, 'generateInvite'])->name('telegram.generate-invite');
        Route::post('/telegram/{telegramGroup}/expire-link', [AdminTelegramController::class, 'expireLink'])->name('telegram.expire-link');
        Route::post('/telegram/{telegramGroup}/send-announcement', [AdminTelegramController::class, 'sendAnnouncement'])->name('telegram.send-announcement');

        Route::get('/announcements', [AdminAnnouncementController::class, 'index'])->name('announcements.index');
        Route::get('/announcements/create', [AdminAnnouncementController::class, 'create'])->name('announcements.create');
        Route::post('/announcements', [AdminAnnouncementController::class, 'store'])->name('announcements.store');
        Route::get('/announcements/{announcement}/edit', [AdminAnnouncementController::class, 'edit'])->name('announcements.edit');
        Route::put('/announcements/{announcement}', [AdminAnnouncementController::class, 'update'])->name('announcements.update');
        Route::delete('/announcements/{announcement}', [AdminAnnouncementController::class, 'destroy'])->name('announcements.destroy');
        Route::post('/announcements/{announcement}/draft', [AdminAnnouncementController::class, 'draft'])->name('announcements.draft');
        Route::post('/announcements/{announcement}/schedule', [AdminAnnouncementController::class, 'schedule'])->name('announcements.schedule');
        Route::post('/announcements/{announcement}/publish', [AdminAnnouncementController::class, 'publish'])->name('announcements.publish');
        Route::post('/announcements/{announcement}/pin', [AdminAnnouncementController::class, 'pin'])->name('announcements.pin');
        Route::post('/announcements/{announcement}/archive', [AdminAnnouncementController::class, 'archive'])->name('announcements.archive');
        Route::post('/announcements/{announcement}/notify', [AdminAnnouncementController::class, 'sendNotification'])->name('announcements.notify');

        Route::get('/reports', [AdminReportController::class, 'index'])->name('reports.index');
        Route::post('/reports', [AdminReportController::class, 'store'])->name('reports.store');
        Route::get('/reports/{reportJob}/download', [AdminReportController::class, 'download'])->name('reports.download');
        Route::get('/marketing', [MarketingOverviewController::class, 'index'])->name('marketing.index');
        Route::get('/support', [SupportOverviewController::class, 'index'])->name('support.index');
        Route::get('/team', [TeamOverviewController::class, 'index'])->name('team.index');
        Route::get('/finance', [FinanceOverviewController::class, 'index'])->name('finance.index');

        Route::get('/settings/{tab?}', [AdminSettingsController::class, 'index'])->name('settings.index');
        Route::put('/settings', [AdminSettingsController::class, 'update'])->name('settings.update');
        Route::get('/system-logs', [SystemLogController::class, 'index'])->name('system-logs.index');

        Route::get('/enrollment-requests', [AdminEnrollmentRequestController::class, 'index'])->name('enrollment-requests.index');
        Route::post('/enrollment-requests/{courseAccessRequest}/approve', [AdminEnrollmentRequestController::class, 'approve'])->name('enrollment-requests.approve');
        Route::post('/enrollment-requests/{courseAccessRequest}/reject', [AdminEnrollmentRequestController::class, 'reject'])->name('enrollment-requests.reject');

        Route::get('/roles', [AdminRoleController::class, 'index'])->name('roles.index');
        Route::put('/roles/{role}', [AdminRoleController::class, 'update'])->name('roles.update');
        Route::get('/audit-logs', [AuditLogController::class, 'index'])->name('audit-logs.index');
        Route::get('/ops', [OpsController::class, 'index'])->name('ops.index');
        Route::get('/comms', [CommsController::class, 'index'])->name('comms.index');
        Route::get('/security', [SecurityController::class, 'index'])->name('security.index');
    });
});
